config/routes.rb
Fotoz::Application.routes.draw do
  resources :details

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  

  
  resources :photos

  resources :albums,:collection => { :move_to_album => :put }
  
  resources :site

  resources :friends

  resource :traveller

   devise_scope :user do 
    root 'site#index'
    get "/users/sign_out" => "devise/sessions#destroy"
   end

      get 'albums/:id/create_zip' => 'albums#create_zip', as: :zip
      get 'upload', to: 'photos#upload_bulk_images', as: :bulk
      get 'download', to: 'site#download'
      get 'explore', to: 'site#explore'
      get 'share', to: 'site#share'
      post 'move_to_album', to: 'albums#move_to_album'
      get 'send_request', to: 'friends#invitation'
      get 'profile', to: 'details#index'
      

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => ["180x130#"] }
  
  #searchable do
  # string :name
  #end
  
  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
      "name" => read_attribute(:avatar_file_name),
      "size" => read_attribute(:avatar_file_size),
      "url" => avatar.url(:original),
      "delete_url" => photos_path,
      "delete_type" => "DELETE",
      #"create_url" => albums_path
    }
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  # GET /photos
  # GET /photos.json
  def index
    
    #@photos = Photo.all
    @photos = current_user.photos.paginate(:page => params[:page], :per_page => 20)
    @album = current_user.albums.all.collect{|p|[p.name]}
    @albums = current_user.albums.all
    
    @call_from = "photos"
    #render :template => 'albums/index'
    
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new()
    @album = params[:album]
  end

  # GET /photos/1/edit
  def edit
  end
  
  def upload_bulk_images
  end

  # POST /photos
  # POST /photos.json
  def create
    #@photo = Photo.new(photo_params)
    @photo = Photo.create( photo_params )
    @album = Album.where("id=#{params[:album_id]}") if params[:album_id]

    respond_to do |format|
      if @photo.save
        #render :text => @photo.inspect and return false
        if params[:album_id]
          format.html { redirect_to @album, notice: 'Photo was successfully uploaded.' }
          format.json { render action: @album, status: :created, location: @album }
        end
        #render :text => @photo.inspect and return false
        #format.html { redirect_to @photo, notice: 'Photo was successfully uploaded.' }
        #format.json { render json:  @photo, status: :created }
        format.html {
         redirect_to albums_path
        }

        #format.html { render albums_path }
        #	format.json { render json: {files: [@photo.to_jq_upload]}, status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end





  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:album_id,:user_id, :name, :description, :location, :privacy, :binary_data, :avatar)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo,:multipart=>true ) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <ul class="thumbnails">
    <li class="span4">
      <% if params[:id] %>
        <%=image_tag (@photo.avatar(:medium))%>
      <%else%>
        <%=image_tag "thumb.png", :alt => "Upload image", :class=>"thumbnail"%>
      <%end%>
    </li>
    </ul>
      <%#=@photo.inspect%>    
      <%= f.file_field :avatar if @photo.id.nil?%><br>
  </div><br/>
  <div class="field">
    <%= f.text_field :name,:placeholder=>"Image title" %>
    <%= f.hidden_field :user_id, :value=>current_user.id%>
    <%if @album.blank?%>
      <%= f.collection_select(:album_id, current_user.albums, :id, :name,:include_blank => 'none' )%>
    <%else%>
      <%= f.hidden_field :album_id, :value=>"#{@album}" %>
    <%end%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :placeholder=>"Image description" %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, :placeholder=>"Where was it taken" %>
  </div>
  <div class="field">
    <%#= f.label :privacy %><br>
    <%#= f.text_field :privacy %>
  </div>
  <div class="field">
    <%#= f.label :binary_data %><br>
    <%#= f.text_field :binary_data %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/photos/_photo_list.html.erb
<%= form_tag move_to_album_path do %>

  <%= will_paginate @photos, :class=>"apple_pagination"%>
  <div style="height:70px;">
    <div class="tag">
      <%if @name.nil?%>
       All Photos
       <%else%>
      <%=@name%>
      <%end%>
      </div>
    <div style="float:left">
      <%= link_to (image_tag("add.png",:width=>"40px",:height=>"40px")), new_photo_path,:title=>"Add Photo",:id=>"addphoto" %>
    </div
    <center>
      <%= submit_tag "move to"%>
      <%= select_tag "album", options_from_collection_for_select(current_user.albums, "id", "name")%>
    </center>
  </div>
  

    <% @photos.each do |photo| %>
    <div class="tilt pic item">
      <span class="play"></span>
      <a class="fancybox" rel="group" href="<%=photo.avatar(:original)%>">
          <%=image_tag(photo.avatar(:thumb))%>
        </a>
        <%#=image_tag("bin.png",:id=>"test",:style=>"display:none;")%>
        <div class="tools">
          <div class="pull-right"><%=link_to(image_tag("cool_icons/delete.png"), photo, method: :delete, data: { confirm: 'Are you sure?' }) %>
          <%= link_to (image_tag("cool_icons/edit.png")), edit_photo_path(photo) %>
          <%=check_box_tag("check#{photo.id}", value = "#{photo.id}", checked = false, options = {})%>
          </div>
        </div>
        <div class="image-name">
          <%unless photo.name.blank?%>
            <%=photo.name%>
          <%else%>
            <%=link_to "<Add Details>", edit_photo_path(photo)%>
          <%end%>

        </div>
    </div>
    <%end%>
  <%end%>
  

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Albums</h3>
    
  </div>
  <%@albums.each do |album|%>
    <div style="float:left">
      <%=link_to (image_tag("photo_album.png",:style=>"width:50px;height:50px;")),album%>
      <p><%=link_to "#{album.name}", albums_path(album)%><br/><%=album.photos.count%> photos</p>
    </div>
  <%end%>
</div>
<div style="float:left;">
<div class="container">
  <div class="row">
    <%=render :partial=>'photo_list'%>
  </div>
</div>
</div>

app/views/photos/new.html.erb
<h1>Add New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<div class="row-fluid">
  <ul class="thumbnails">
    <li class="span4">
      <div class="thumbnail">
        <%= image_tag @photo.avatar(:medium) %>
        <p><%= @photo.name %></p>
        <p><%= @photo.description %></p>
        <p><%= @photo.location %></p>
        <p><%= @photo.privacy %></p>
        <p><%= @photo.binary_data%></p>
       </div>
      </div>
    </li>
  </ul>
</div>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', albums_path %>

app/views/photos/upload_bulk_images.html.erb
<div class="container">
  <h2>Upload file</h2>
  <%= form_for Photo.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :avatar,multiple: true, name: "photo[avatar]"  %>
          <%= f.hidden_field :user_id,:value=>current_user.id%>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      
      <h3>Drag and Drop your images here !!</h3>
      
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped">
        <tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

</div>
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty2222222 file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
          {%=file.name%}
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      // 
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'), 
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>