config/routes.rb
Fotoz::Application.routes.draw do
  resources :details

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  

  
  resources :photos

  resources :albums,:collection => { :move_to_album => :put }
  
  resources :site

  resources :friends

  resource :traveller

   devise_scope :user do 
    root 'site#index'
    get "/users/sign_out" => "devise/sessions#destroy"
   end

      get 'albums/:id/create_zip' => 'albums#create_zip', as: :zip
      get 'upload', to: 'photos#upload_bulk_images', as: :bulk
      get 'download', to: 'site#download'
      get 'explore', to: 'site#explore'
      get 'share', to: 'site#share'
      post 'move_to_album', to: 'albums#move_to_album'
      get 'send_request', to: 'friends#invitation'
      get 'profile', to: 'details#index'
      

  

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authenticate_user!

  def index
    
  end

  def download
    @album =  current_user.albums.all
  end

  def explore

  end

  def share
    
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/download.html.erb
<div class="download">
	<div class="download-bg">
		<h2>Download Direct :</h2>
	</div>
	    <%count = 0%>
		<%@album.each do |album| %>
		<%if count%2 == 0%>
		  <div class="download-even">
		<%else%>
		  <div class="download-odd">
		<%end%>
	        <p style="float:left;margin-left: 50px;width:100px;"> <%= album.name.capitalize%> </p>&nbsp;|&nbsp;
	        <p style="float:right;margin-right: 50px;"> <%= link_to 'Download', zip_path(album)%> </p>
	      </div>
	      <%count = count + 1%>
		<%end%>
	
</div>

app/views/site/explore.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "explore.html" %>

app/views/site/index.html.erb
<%if user_signed_in? %>
  <div class="login-header">
   <% if !flash[:notice].blank? %>
    <div class="alert-welcome alert-success" id="test">
      <strong>Welcome!</strong> <%=flash[:notice]%><%flash[:notice]= nil%>
    </div>
    <%end%>
  </div>
<%end%><br/>

<%=link_to "Update Profile",profile_path%>
    <div class="main-cover row">
      <div class="main-cover-border">
        <div class="row-fluid show-grid">
          <div class="main-menu" id = "upload">
            <div class="main-text">
              <%=link_to (image_tag("upload.png")),bulk_path%>
              <%=link_to "Upload",bulk_path%>
            </div>
          </div>
          <div class="main-menu" id = "explore">
            <div class="main-text">
              <%=link_to (image_tag("explore.png")),albums_path%>
              <%=link_to 'Explore',albums_path%>
            </div>
          </div>
        </div>

        <div class="row-fluid show-grid">
          <div class="main-menu" id = "share">
            <div class="main-text">
              <%=link_to (image_tag("share.png")),share_path%>
              <%=link_to 'Share',share_path%>
            </div>
          </div>
          <div class="main-menu" id = "download">
            <div class="main-text">
              <%=link_to (image_tag("download.png")),download_path%>
              <%=link_to 'Download',download_path%>
            </div>
          </div>
        </div>
      </div>    
      
    </div>
    
    <%flash[:notice]= nil%>
    
    
    

app/views/site/share.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "share.html" %>