config/routes.rb
Fotoz::Application.routes.draw do
  resources :details

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  

  
  resources :photos

  resources :albums,:collection => { :move_to_album => :put }
  
  resources :site

  resources :friends

  resource :traveller

   devise_scope :user do 
    root 'site#index'
    get "/users/sign_out" => "devise/sessions#destroy"
   end

      get 'albums/:id/create_zip' => 'albums#create_zip', as: :zip
      get 'upload', to: 'photos#upload_bulk_images', as: :bulk
      get 'download', to: 'site#download'
      get 'explore', to: 'site#explore'
      get 'share', to: 'site#share'
      post 'move_to_album', to: 'albums#move_to_album'
      get 'send_request', to: 'friends#invitation'
      get 'profile', to: 'details#index'
      

  

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
  	@user_details = current_user.detail if !current_user.detail.blank?
  end	
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
  
    <div class="hero-unit">
        <h1>Welcome User</h1>
        <p class="lead">Please update your profile.</p>
        <%= form_for(@user_details) do |f| %>
  <% if @user_details.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_details.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @user_details.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="hero-unit">
  <div class="field">
    <%#= f.label :name %><br>
    <%= f.text_field :name ,:placeholder=>"Album Name"%>
  </div>
  <div class="field">
    <%#= f.label :description %><br>
    <%= f.text_area :age ,:placeholder=>"Description" %>
  </div>
  <div class="field">
    <%#= f.label :location %><br>
    <%= f.text_field :sex ,:placeholder=>"Where was it taken"%>
  </div>
  <div class="field">
    <%#= f.label :privacy %><br>
    <%= f.text_field :address1 ,:placeholder=>"Address1"%>
  </div>
  <div class="field">
    <%#= f.label :privacy %><br>
    <%= f.text_field :address2 ,:placeholder=>"Address2"%>  
  </div>

  <div class="field">
    <%#= f.label :privacy %><br>
    <%= f.text_field :profession ,:placeholder=>"Profession"%>  
  </div>
  <div class="modal-footer" >
    
    <%= link_to 'Back', albums_path,:class=>"btn" %>
    <%= f.submit :class=>"btn btn-primary"%>
  </div>
</div>

<% end %>

        
        <p><a href="#" class="btn btn-success btn-large">Submit</a></p>
    </div>
  

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @detail.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @detail.address %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>