config/routes.rb
Fotoz::Application.routes.draw do
  resources :details

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  

  
  resources :photos

  resources :albums,:collection => { :move_to_album => :put }
  
  resources :site

  resources :friends

  resource :traveller

   devise_scope :user do 
    root 'site#index'
    get "/users/sign_out" => "devise/sessions#destroy"
   end

      get 'albums/:id/create_zip' => 'albums#create_zip', as: :zip
      get 'upload', to: 'photos#upload_bulk_images', as: :bulk
      get 'download', to: 'site#download'
      get 'explore', to: 'site#explore'
      get 'share', to: 'site#share'
      post 'move_to_album', to: 'albums#move_to_album'
      get 'send_request', to: 'friends#invitation'
      get 'profile', to: 'details#index'
      

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Fotoz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="main-background">
      <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#" id="logo"><%=image_tag("my_photoz2.png")%></a>
          <div class="nav-collapse collapse" >
          <%if user_signed_in?%>
            <p class="navbar-text pull-right">
              Logged in as <%=current_user.email%>&nbsp;|&nbsp;&nbsp;<%=link_to"Signout",destroy_user_session_path%>
            </p>
            <ul class="nav">
              <li class="active"><%=link_to "Home",root_path%></li>
              <li><%=link_to "Gallery",albums_path%></li>
              <li><%#=link_to "Photos",photos_path%></li>
              <li><%=link_to "Friends",friends_path%></li>
            </ul>
            <form class="navbar-search pull-right" style="margin-right:20px;">
              <input type="text" class="search-query" placeholder="Search">
            </form>
            <%end%>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid" style="margin-top:30px;">
      <%= yield %>
    </div>

</body>
</html>


 



    